/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffb2b6",
        "tertiary-container": "#003623",
        "surface-container-lowest": "#ffffff",
        "surface": "#fcf9f3",
        "surface-variant": "#e5e2dc",
        "secondary-container": "#e9c0fd",
        "on-background": "#1c1c18",
        "on-primary-fixed": "#40000d",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdada",
        "primary-fixed-dim": "#ffb2b6",
        "on-secondary-container": "#6c4b7f",
        "on-secondary-fixed": "#2b0c3e",
        "on-tertiary-container": "#68a284",
        "tertiary-fixed-dim": "#98d3b3",
        "surface-container": "#f0eee8",
        "on-primary-container": "#e1767e",
        "outline-variant": "#dbc0c1",
        "surface-tint": "#9c4049",
        "inverse-on-surface": "#f3f0ea",
        "secondary-fixed-dim": "#e0b8f4",
        "secondary": "#735186",
        "surface-dim": "#dcdad4",
        "background": "#fcf9f3",
        "secondary-fixed": "#f4d9ff",
        "surface-container-highest": "#e5e2dc",
        "outline": "#887272",
        "on-surface-variant": "#554243",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#fcf9f3",
        "on-secondary": "#ffffff",
        "inverse-surface": "#31312d",
        "tertiary-fixed": "#b3f0ce",
        "primary": "#3d000c",
        "on-tertiary-fixed-variant": "#145038",
        "on-primary-fixed-variant": "#7e2933",
        "on-error": "#ffffff",
        "primary-container": "#5d101d",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#001f12",
        "error-container": "#ffdad6",
        "on-surface": "#1c1c18",
        "surface-container-low": "#f6f3ed",
        "on-secondary-fixed-variant": "#593a6d",
        "on-error-container": "#93000a",
        "surface-container-high": "#ebe8e2"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1440px",
        "stack-md": "16px",
        "margin-desktop": "80px",
        "section-gap": "120px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "gutter": "32px"
      },
      fontFamily: {
        "headline-md": ["Libre Caslon Text", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "label-sm": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.1em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
